
    create table certificato_medico (
        data_certificato date,
        id integer generated by default as identity,
        tipo_certificato boolean,
        primary key (id)
    );

    create table socio (
        certificato_id integer unique,
        id integer generated by default as identity,
        codice_fiscale varchar(16) not null unique,
        cognome varchar(100) not null,
        nome varchar(100) not null,
        email varchar(255),
        primary key (id)
    );

    alter table if exists socio 
       add constraint fk_socio_certificato 
       foreign key (certificato_id) 
       references certificato_medico;
