
    create table abbonamento_attivita (
        abbonamento_id integer not null,
        attivita_id integer not null
    );

    create table abbonamento_socio (
        data_iscrizione date not null,
        durata_validita integer not null,
        id integer generated by default as identity,
        id_socio integer,
        primary key (id)
    );

    create table attivita (
        id integer generated by default as identity,
        prezzo_attivita bigint not null,
        descrizione_attivita varchar(100) not null,
        primary key (id)
    );

    create table certificato_medico (
        data_certificato date,
        id integer generated by default as identity,
        tipo_certificato boolean,
        primary key (id)
    );

    create table socio (
        certificato_id integer unique,
        id integer generated by default as identity,
        codice_fiscale varchar(16) not null unique,
        cognome varchar(100) not null,
        nome varchar(100) not null,
        email varchar(255),
        primary key (id)
    );

    alter table if exists abbonamento_attivita 
       add constraint FK853iwjge5sco7nac3v8pvs72v 
       foreign key (attivita_id) 
       references attivita;

    alter table if exists abbonamento_attivita 
       add constraint FK7slwjgyb7wchv5gnm07g9m6v1 
       foreign key (abbonamento_id) 
       references abbonamento_socio;

    alter table if exists abbonamento_socio 
       add constraint fk_abbonamento_socio 
       foreign key (id_socio) 
       references socio;

    alter table if exists socio 
       add constraint fk_socio_certificato 
       foreign key (certificato_id) 
       references certificato_medico;
