socio.cognome.like=select s from Socio s where cognome like :cognome%

socio.selectByAttivita=select s from Socio s \
inner join s.abbonamento abb \
inner join abb.attivita att \
where att.id = :id

socio.selectByFilter = select s from Socio s \
left join s.abbonamento abb \
left join abb.attivita att \
where (:id is null or s.id = :id) \
and (:nome is null or nome like :nome%) \
and (:cognome is null or cognome like :cognome%) \
and (:attivita is null or att.id = :attivita) \
order by cognome asc